### ISSUE TITLE
Users don't seem to need the Antlr generator

### ISSUE THREAD

**Issue by svenefftinge** [pellepelster/myadmin#10]
on the website it is stated that people need to install the antlr generator for using MyAdmin.
AFAIK myadmin comes with ready to use dsls, in which case antlr-gen is not needed.
It's only needed if you want to build a new language with Xtext.

**Comment by pellepelster** [comment]
You're right ANTLR is only needed for development not during runtime, I removed the hint from the website as well as the preconfigured distros.
